title: 
email: your-email@example.com
description: by Authors # Author names go here.

baseurl: 

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
