title: Curry and Chips
email: your-email@example.com
description: by Nick Corso, Shulamit Falk, Lakyn Wilson

baseurl: 

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
